runtime: python38 # or python37 for Python 3.7
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
    python_version: 3
manual_scaling:
    instances: 1
env_variables:
  SLACK_TOKEN: "xoxb-842063672404-2923114979617-QJt0Ta57JlPmTxjuLP1iESW8"